package:
  name: hdf5
  version: 1.8.13

source:
  fn: hdf5-1.8.13.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/src/hdf5-1.8.13.tar.bz2
  md5: b060bb137d6bd8accf8f0c4c59d2746d

build:
  number: 0

requirements:
  build:
    - zlib

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD
  summary: 'Hierarchical Data Format (HDF) is a set of file formats designed to store and organize large amounts of numerical data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
