package:
  name: hdf5
  version: 1.8.13

source:
  fn: hdf5-1.8.13.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.13/src/hdf5-1.8.13.tar.bz2
  md5: c03426e9e77d7766944654280b467289

build:
  number: 0

requirements:
  build:
    - zlib

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD
  summary: 'Hierarchical Data Format (HDF) is a set of file formats designed to store and organize large amounts of numerical data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
